[profile.default]
solc = "0.8.23"
evm_version = "shanghai"

optimizer = true
optimizer_runs = 1000000
src = 'contracts/src'
out = 'dist/contracts'
libs = ['contracts/lib']

via_ir = true
eth-rpc-url = 'http://localhost:8545'

fs_permissions = [{ access = "read", path = "dist/contracts" }, { access = "read-write", path = ".forge-snapshots/" }]

extra_output = ['storageLayout']
